### PIAIC151420 Syed A Naqvi

In [2]:
import numpy as np

In [3]:
np.__version__

'1.19.2'

In [4]:
l = range(1000000)

In [5]:
d = np.arange(1000000)

In [6]:
%time for i in range(1,10): r=[x*2 for x in l]

Wall time: 656 ms


In [7]:
%time for i in range(1,10): r=d*2

Wall time: 27.9 ms


In [8]:
k= np.arange(24)
k

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [9]:
x = np.array([1, 2, 3, 4, 5, 6])
x

array([1, 2, 3, 4, 5, 6])

In [11]:
y = np.array([[1,0,0,0],[0,0,0,1]])
y

array([[1, 0, 0, 0],
       [0, 0, 0, 1]])

In [13]:
np.zeros(2)

array([0., 0.])

In [14]:
np.ones(2)

array([1., 1.])

In [15]:
np.ones(6)

array([1., 1., 1., 1., 1., 1.])

In [16]:
np.empty(4)

array([2.12199579e-314, 6.79038653e-313, 4.98018171e-321, 6.95314444e-310])

In [17]:
np.arange(1, 5, 12)

array([1])

In [18]:
np.arange(2, 19, 2)

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18])

In [19]:
np.linspace(0, 10, num=5)

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [20]:
x = np.ones(2, dtype=np.int64)
x

array([1, 1], dtype=int64)

In [21]:
arr = np.array([2, 1, 5, 3, 7, 4, 6, 8])

In [22]:
np.sort(arr)

array([1, 2, 3, 4, 5, 6, 7, 8])

In [24]:
a = np.array([1, 2, 3, 4])
b = np.array([5, 6, 7, 8])

In [25]:
np.concatenate((a, b))

array([1, 2, 3, 4, 5, 6, 7, 8])

In [33]:
x = np.array([[10, 20], [30,40]])
y = np.array([[1/5, 1/2]])
np.concatenate((x,y))

array([[10. , 20. ],
       [30. , 40. ],
       [ 0.2,  0.5]])

In [34]:
np.concatenate((a, b), axis=0)

array([1, 2, 3, 4, 5, 6, 7, 8])

In [42]:
p = np.array( [[[2, 3, 6], [1,2,3],], [[1,3,5],[0,2,4]], [[-1,-2,-3],[-2,-4,-6]]])

In [43]:
np.ndim(p)

3

In [44]:
p

array([[[ 2,  3,  6],
        [ 1,  2,  3]],

       [[ 1,  3,  5],
        [ 0,  2,  4]],

       [[-1, -2, -3],
        [-2, -4, -6]]])

In [45]:
p.size

18

In [46]:
p.shape

(3, 2, 3)

In [49]:
p

array([[[ 2,  3,  6],
        [ 1,  2,  3]],

       [[ 1,  3,  5],
        [ 0,  2,  4]],

       [[-1, -2, -3],
        [-2, -4, -6]]])

In [53]:
p.reshape(3,6)

array([[ 2,  3,  6,  1,  2,  3],
       [ 1,  3,  5,  0,  2,  4],
       [-1, -2, -3, -2, -4, -6]])

In [56]:
d = np.array([1, 2, 3, 4, 5, 6])

In [57]:
d.shape

(6,)

In [58]:
d.reshape(2,3)

array([[1, 2, 3],
       [4, 5, 6]])

In [59]:
d.reshape(3,2)

array([[1, 2],
       [3, 4],
       [5, 6]])

In [66]:
dcol = d[:, np.newaxis]
dcol

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6]])

In [61]:
d4.shape

(1, 6)

In [67]:
drow = d[np.newaxis,:]
drow

array([[1, 2, 3, 4, 5, 6]])

In [68]:
e = np.expand_dims(a, axis=1)

In [69]:
e.shape

(4, 1)

In [72]:
data = np.array([1,2,3])

In [73]:
data

array([1, 2, 3])

In [75]:
data[1:]

array([2, 3])

In [76]:
data[:2]

array([1, 2])

In [81]:
f = np.array([[1 , 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])

In [82]:
f

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [85]:
print(f[f < 10])

[1 2 3 4 5 6 7 8 9]


In [86]:
five_up = (f >= 5)

In [87]:
five_up

array([[False, False, False, False],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True]])

In [88]:
print(f[five_up])

[ 5  6  7  8  9 10 11 12]


In [89]:
divisible_by_2 = f[f%2==0]

In [90]:
divisible_by_2

array([ 2,  4,  6,  8, 10, 12])

In [91]:
print(divisible_by_2)

[ 2  4  6  8 10 12]


In [92]:
f = np.array([[1 , 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])

In [93]:
f

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [94]:
g = np.array([[-1 , 2, -3, 4], [5, -6, 7, -8], [-4, -5, -1, -2]])

In [95]:
g

array([[-1,  2, -3,  4],
       [ 5, -6,  7, -8],
       [-4, -5, -1, -2]])

In [97]:
np.vstack((f,g))

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [-1,  2, -3,  4],
       [ 5, -6,  7, -8],
       [-4, -5, -1, -2]])

In [98]:
np.hstack((f,g))

array([[ 1,  2,  3,  4, -1,  2, -3,  4],
       [ 5,  6,  7,  8,  5, -6,  7, -8],
       [ 9, 10, 11, 12, -4, -5, -1, -2]])

In [103]:
h = np.arange(1, 25).reshape(2, 12)

In [104]:
h

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24]])

In [105]:
np.hsplit(h, 3)

[array([[ 1,  2,  3,  4],
        [13, 14, 15, 16]]),
 array([[ 5,  6,  7,  8],
        [17, 18, 19, 20]]),
 array([[ 9, 10, 11, 12],
        [21, 22, 23, 24]])]

In [106]:
np.hsplit(h, (3,4))

[array([[ 1,  2,  3],
        [13, 14, 15]]),
 array([[ 4],
        [16]]),
 array([[ 5,  6,  7,  8,  9, 10, 11, 12],
        [17, 18, 19, 20, 21, 22, 23, 24]])]

In [109]:
data = np.array([1,2])

In [110]:
ones = np.ones(2, dtype=int)

In [111]:
data + ones

array([2, 3])

In [112]:
data - ones

array([0, 1])

In [113]:
data

array([1, 2])

In [114]:
c = np.array([1,2,1,3,4,5,2,1])

In [117]:
unique_values = np.unique(c)

In [118]:
unique_values

array([1, 2, 3, 4, 5])

In [120]:
data = np.array([1,2,3,4,5,6])

In [121]:
data.reshape(2,3)

array([[1, 2, 3],
       [4, 5, 6]])

In [122]:
data.reshape(3,2)

array([[1, 2],
       [3, 4],
       [5, 6]])

In [123]:
d5 = np.flip(data, axis=0)

In [124]:
d5

array([6, 5, 4, 3, 2, 1])

In [144]:
data = np.array([1,2,3,4,5,6])

In [145]:
data

array([1, 2, 3, 4, 5, 6])

In [146]:
d6

array([1, 2, 3, 4, 5, 6])

In [147]:
d7 = data.flatten()

In [148]:
d7

array([1, 2, 3, 4, 5, 6])

In [149]:
data

array([1, 2, 3, 4, 5, 6])

In [150]:
np.full((3, 3), True, dtype=bool) #

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

In [151]:
arr = np.arange(10)
out = np.where(arr % 2 == 1, -1, arr)
print(arr)
out

[0 1 2 3 4 5 6 7 8 9]


array([ 0, -1,  2, -1,  4, -1,  6, -1,  8, -1])

In [152]:
a = np.arange(10).reshape(2,-1)
b = np.repeat(1, 10).reshape(2,-1)
np.concatenate([a, b], axis=0)
np.vstack([a, b])

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [154]:
a = np.array([1,2,3])
np.r_[np.repeat(a, 3), np.tile(a, 3)]  # np.tile

array([1, 1, 1, 2, 2, 2, 3, 3, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3])

In [156]:
a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])
np.intersect1d(a,b)  # np.intersect1d

array([2, 4])

In [157]:
a = np.array([1,2,3,4,5])
b = np.array([5,6,7,8,9])

# From 'a' remove all of 'b'
np.setdiff1d(a,b)

array([1, 2, 3, 4])

In [158]:
a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])

np.where(a == b)

(array([1, 3, 5, 7], dtype=int64),)

In [159]:
rand_arr = np.random.randint(low=5, high=10, size=(5,3)) + np.random.random((5,3))

In [160]:
print(rand_arr)

[[9.10159025 7.97426585 6.92857816]
 [8.80882988 9.36712532 6.92773514]
 [5.82598479 7.08099048 7.11718914]
 [6.31945792 7.74635125 8.29619955]
 [6.31756156 5.76994978 9.25042194]]


In [162]:
rand_num = np.random.random((5,3))
print(rand_num)

[[0.16202133 0.20126294 0.73503127]
 [0.74885867 0.76286788 0.48481738]
 [0.52570601 0.51161362 0.4811477 ]
 [0.69971076 0.74608737 0.17982492]
 [0.42061314 0.36874028 0.24546758]]


In [163]:
np.random.seed(100)
rand_n2sci = np.random.random([3,3])/1e3
rand_n2sci

array([[5.43404942e-04, 2.78369385e-04, 4.24517591e-04],
       [8.44776132e-04, 4.71885619e-06, 1.21569121e-04],
       [6.70749085e-04, 8.25852755e-04, 1.36706590e-04]])

In [164]:
np.set_printoptions(threshold=6)
a = np.arange(15)
a

array([ 0,  1,  2, ..., 12, 13, 14])

Added Jupyter Notebook for Homework